using System;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.EntityFrameworkCore.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace TP_WebServicesGraphQL_Docker.Migrations
{
    /// <inheritdoc />
    public partial class dummydata : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Editors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySQL:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Editors", x => x.Id);
                })
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Games",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySQL:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false),
                    Genres = table.Column<string>(type: "longtext", nullable: false),
                    PublicationDate = table.Column<DateTime>(type: "datetime(6)", nullable: false),
                    Platforms = table.Column<string>(type: "longtext", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Games", x => x.Id);
                })
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Studios",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySQL:ValueGenerationStrategy", MySQLValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(type: "varchar(128)", maxLength: 128, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Studios", x => x.Id);
                })
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "GameEditors",
                columns: table => new
                {
                    EditorsId = table.Column<int>(type: "int", nullable: false),
                    GamesId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GameEditors", x => new { x.EditorsId, x.GamesId });
                    table.ForeignKey(
                        name: "FK_GameEditors_Editors_EditorsId",
                        column: x => x.EditorsId,
                        principalTable: "Editors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_GameEditors_Games_GamesId",
                        column: x => x.GamesId,
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "GameStudios",
                columns: table => new
                {
                    GamesId = table.Column<int>(type: "int", nullable: false),
                    StudiosId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GameStudios", x => new { x.GamesId, x.StudiosId });
                    table.ForeignKey(
                        name: "FK_GameStudios_Games_GamesId",
                        column: x => x.GamesId,
                        principalTable: "Games",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_GameStudios_Studios_StudiosId",
                        column: x => x.StudiosId,
                        principalTable: "Studios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySQL:Charset", "utf8mb4");

            migrationBuilder.InsertData(
                table: "Editors",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Cassin - Lynch" },
                    { 2, "Shanahan - Kreiger" },
                    { 3, "Walker - Rodriguez" },
                    { 4, "Torphy, Zboncak and Beer" },
                    { 5, "Romaguera and Sons" },
                    { 6, "Weber - Koelpin" },
                    { 7, "Lueilwitz Group" },
                    { 8, "Turcotte LLC" },
                    { 9, "Hagenes and Sons" },
                    { 10, "Cassin - O'Kon" },
                    { 11, "Olson Group" },
                    { 12, "Miller Inc" },
                    { 13, "Boyer, Nienow and O'Hara" },
                    { 14, "Schuppe Group" },
                    { 15, "Kassulke, Romaguera and Ortiz" },
                    { 16, "Turcotte - Tremblay" },
                    { 17, "Morar - Watsica" },
                    { 18, "Hettinger, Predovic and Schimmel" },
                    { 19, "Adams and Sons" },
                    { 20, "Howell Inc" },
                    { 21, "Kihn and Sons" },
                    { 22, "Nicolas and Sons" },
                    { 23, "Wunsch and Sons" },
                    { 24, "Schroeder and Sons" },
                    { 25, "Stoltenberg, Effertz and Lakin" },
                    { 26, "Jerde LLC" },
                    { 27, "Thiel Inc" },
                    { 28, "Pfeffer and Sons" },
                    { 29, "Lemke - Effertz" },
                    { 30, "Marquardt, Schinner and Wilkinson" },
                    { 31, "McGlynn - Wintheiser" },
                    { 32, "Tillman - Hudson" },
                    { 33, "Strosin - Bailey" },
                    { 34, "Bechtelar and Sons" },
                    { 35, "Wintheiser and Sons" },
                    { 36, "Streich and Sons" },
                    { 37, "Simonis - Ward" },
                    { 38, "Johnson - Lakin" },
                    { 39, "Stanton - Cronin" },
                    { 40, "Balistreri - Ullrich" },
                    { 41, "Kilback and Sons" },
                    { 42, "Konopelski Group" },
                    { 43, "Jacobson, Dibbert and Doyle" },
                    { 44, "Gorczany, Crooks and Crooks" },
                    { 45, "Hudson, Goyette and Gerhold" },
                    { 46, "Ziemann - Gislason" },
                    { 47, "Zulauf, Swift and Smith" },
                    { 48, "Waters - White" },
                    { 49, "Moen Inc" },
                    { 50, "Nitzsche - Prosacco" },
                    { 51, "Reilly, Runte and Renner" },
                    { 52, "Littel - Mraz" },
                    { 53, "MacGyver, Hilpert and Gottlieb" },
                    { 54, "Labadie, Boyer and Marquardt" },
                    { 55, "Gutkowski Inc" },
                    { 56, "Robel Group" },
                    { 57, "Stanton, DuBuque and Beer" },
                    { 58, "Wiza Inc" },
                    { 59, "Corwin and Sons" },
                    { 60, "McGlynn, Wisoky and Abernathy" },
                    { 61, "Haag, Streich and Hansen" },
                    { 62, "Marvin Group" },
                    { 63, "Rempel, Hermann and Weimann" },
                    { 64, "Parisian, Armstrong and Boyer" },
                    { 65, "Johnston, O'Conner and Schowalter" },
                    { 66, "Labadie Inc" },
                    { 67, "Kertzmann - Russel" },
                    { 68, "Gerlach Inc" },
                    { 69, "Windler, Rath and Jacobi" },
                    { 70, "Streich, Beier and Jaskolski" },
                    { 71, "Champlin, Murray and Barton" },
                    { 72, "Jenkins, Walter and Roob" },
                    { 73, "Hilpert Inc" },
                    { 74, "Bergstrom LLC" },
                    { 75, "McKenzie - Hayes" },
                    { 76, "Little - Romaguera" },
                    { 77, "Reichel LLC" },
                    { 78, "McGlynn, Crooks and Robel" },
                    { 79, "Parisian, Jaskolski and O'Kon" },
                    { 80, "Emmerich - Block" },
                    { 81, "Strosin - Howe" },
                    { 82, "Runolfsdottir LLC" },
                    { 83, "Bahringer Group" },
                    { 84, "Pouros - Metz" },
                    { 85, "Luettgen, Oberbrunner and Kemmer" },
                    { 86, "Schneider Inc" },
                    { 87, "Howe - Reichel" },
                    { 88, "Krajcik, Kulas and Gleason" },
                    { 89, "Thompson Inc" },
                    { 90, "Nitzsche - Kuhlman" },
                    { 91, "Miller - Moen" },
                    { 92, "Wilderman - Yost" },
                    { 93, "Nikolaus - Conroy" },
                    { 94, "Bartoletti - Gerlach" },
                    { 95, "Collins and Sons" },
                    { 96, "Huels, Hoeger and Bauch" },
                    { 97, "Smith and Sons" },
                    { 98, "Berge - Russel" },
                    { 99, "Langworth Group" },
                    { 100, "Gaylord - Powlowski" },
                    { 101, "Bergstrom Group" },
                    { 102, "Blanda - Tremblay" },
                    { 103, "Stehr and Sons" },
                    { 104, "Johnston LLC" },
                    { 105, "Stiedemann, Gorczany and Bogan" },
                    { 106, "Rodriguez - Beer" },
                    { 107, "Willms, Ward and Mueller" },
                    { 108, "Schaefer LLC" },
                    { 109, "O'Hara - Ziemann" },
                    { 110, "Feil - Ruecker" },
                    { 111, "Crist - Ward" },
                    { 112, "Tillman - Rutherford" },
                    { 113, "Stark - Purdy" },
                    { 114, "Fahey and Sons" },
                    { 115, "Green, Satterfield and Hagenes" },
                    { 116, "Kozey LLC" },
                    { 117, "Haley, Marks and Beer" },
                    { 118, "Senger Inc" },
                    { 119, "Abshire - Connelly" },
                    { 120, "Carter - Shanahan" },
                    { 121, "Murray, Bartoletti and Sauer" },
                    { 122, "Heaney - Rau" },
                    { 123, "Bogan LLC" },
                    { 124, "Lowe Inc" },
                    { 125, "Beahan - Gutmann" },
                    { 126, "Legros - Barrows" },
                    { 127, "Schoen LLC" },
                    { 128, "Lowe, Abernathy and Orn" },
                    { 129, "Dickinson - Hane" },
                    { 130, "Kassulke - Emmerich" },
                    { 131, "Parker - Lehner" },
                    { 132, "Legros and Sons" },
                    { 133, "Bartell, Kovacek and Kshlerin" },
                    { 134, "Rowe, Dach and Schinner" },
                    { 135, "O'Hara, O'Keefe and Medhurst" },
                    { 136, "Sanford, Gutkowski and Swaniawski" },
                    { 137, "Ebert Group" },
                    { 138, "Schinner - West" },
                    { 139, "Blanda and Sons" },
                    { 140, "Greenfelder Inc" },
                    { 141, "Ziemann, Cartwright and Price" },
                    { 142, "Glover Group" },
                    { 143, "Strosin - Beahan" },
                    { 144, "Auer and Sons" },
                    { 145, "Jacobi Inc" },
                    { 146, "Watsica - Wyman" },
                    { 147, "Brekke LLC" },
                    { 148, "Hand - Gusikowski" },
                    { 149, "Smith, Kshlerin and Pouros" },
                    { 150, "Koepp, Schaden and O'Hara" },
                    { 151, "Terry - Romaguera" },
                    { 152, "Weber, Hauck and Orn" },
                    { 153, "Franecki - Dickens" },
                    { 154, "Zboncak - Batz" },
                    { 155, "Kreiger - Fritsch" },
                    { 156, "Wisozk - Beahan" },
                    { 157, "Stoltenberg - Marks" },
                    { 158, "Nikolaus, Lehner and Towne" },
                    { 159, "Lynch - O'Connell" },
                    { 160, "Bernhard Group" },
                    { 161, "Nienow Inc" },
                    { 162, "Hermann - Barrows" },
                    { 163, "Ernser - Stark" },
                    { 164, "Nikolaus, Sipes and Price" },
                    { 165, "Crooks, Huels and Bogan" },
                    { 166, "Hermann - Wehner" },
                    { 167, "Langworth, O'Kon and Jast" },
                    { 168, "Lynch and Sons" },
                    { 169, "Kirlin, Kovacek and Prohaska" },
                    { 170, "Wiegand, Wiegand and Daugherty" },
                    { 171, "Kling Inc" },
                    { 172, "Shanahan - Lowe" },
                    { 173, "Strosin and Sons" },
                    { 174, "Lueilwitz and Sons" },
                    { 175, "Krajcik, Torphy and O'Connell" },
                    { 176, "Grimes and Sons" },
                    { 177, "Marquardt Group" },
                    { 178, "Jacobs - Gerhold" },
                    { 179, "Quigley, Trantow and Gutkowski" },
                    { 180, "Paucek and Sons" },
                    { 181, "Swaniawski - Jacobi" },
                    { 182, "Lemke, Connelly and Kris" },
                    { 183, "Bruen - Lockman" },
                    { 184, "Roberts - Schaefer" },
                    { 185, "Weber - Kilback" },
                    { 186, "Fisher Group" },
                    { 187, "Hilll - Runolfsson" },
                    { 188, "Lang - O'Reilly" },
                    { 189, "Walsh and Sons" },
                    { 190, "Gutmann, Huels and Crooks" },
                    { 191, "Rogahn LLC" },
                    { 192, "Towne, Stamm and Farrell" },
                    { 193, "Tremblay - Yundt" },
                    { 194, "Stoltenberg, Beer and Volkman" },
                    { 195, "Von and Sons" },
                    { 196, "Rolfson Group" },
                    { 197, "Beatty - Schuster" },
                    { 198, "Glover, Gulgowski and Denesik" },
                    { 199, "Johnson Inc" },
                    { 200, "Bauch, Ullrich and Quitzon" }
                });

            migrationBuilder.InsertData(
                table: "Games",
                columns: new[] { "Id", "Genres", "Name", "Platforms", "PublicationDate" },
                values: new object[,]
                {
                    { 1, "fugit,recusandae,nemo,quia", "Handmade Frozen Pants", "facere,ut,qui,excepturi", new DateTime(2024, 5, 5, 18, 56, 24, 156, DateTimeKind.Local).AddTicks(4175) },
                    { 2, "quasi,qui,ipsum,quia", "Licensed Plastic Hat", "voluptas,culpa,omnis,sunt", new DateTime(2024, 9, 21, 18, 51, 30, 627, DateTimeKind.Local).AddTicks(552) },
                    { 3, "omnis,est,ut,voluptatem", "Incredible Frozen Car", "velit,qui,aut,quisquam", new DateTime(2024, 8, 8, 9, 23, 53, 852, DateTimeKind.Local).AddTicks(5790) },
                    { 4, "amet,ipsam,natus,saepe", "Sleek Wooden Car", "aspernatur,excepturi,nisi,modi", new DateTime(2024, 5, 22, 8, 9, 15, 98, DateTimeKind.Local).AddTicks(7598) },
                    { 5, "fugit,id,et,blanditiis", "Generic Cotton Chair", "voluptatem,repudiandae,fuga,qui", new DateTime(2024, 10, 13, 20, 59, 27, 544, DateTimeKind.Local).AddTicks(1265) },
                    { 6, "non,quisquam,quidem,nam", "Small Plastic Chair", "molestiae,tempore,vel,cumque", new DateTime(2024, 7, 26, 4, 36, 37, 947, DateTimeKind.Local).AddTicks(5751) },
                    { 7, "aliquam,commodi,in,magni", "Rustic Rubber Computer", "enim,facilis,dolor,molestiae", new DateTime(2024, 4, 1, 13, 9, 23, 316, DateTimeKind.Local).AddTicks(4792) },
                    { 8, "non,unde,qui,eum", "Fantastic Soft Table", "eos,et,molestiae,consequatur", new DateTime(2023, 12, 31, 8, 24, 11, 394, DateTimeKind.Local).AddTicks(5326) },
                    { 9, "et,fugit,id,quia", "Incredible Concrete Cheese", "fugit,debitis,assumenda,minus", new DateTime(2024, 3, 28, 8, 59, 18, 912, DateTimeKind.Local).AddTicks(9986) },
                    { 10, "ipsum,quasi,sed,pariatur", "Incredible Cotton Chair", "libero,quibusdam,et,ipsam", new DateTime(2024, 5, 15, 12, 41, 49, 882, DateTimeKind.Local).AddTicks(9679) },
                    { 11, "est,in,ex,error", "Handmade Cotton Cheese", "velit,pariatur,sit,quo", new DateTime(2024, 5, 3, 13, 30, 30, 188, DateTimeKind.Local).AddTicks(6356) },
                    { 12, "quidem,reiciendis,et,voluptas", "Unbranded Soft Cheese", "pariatur,ab,sint,adipisci", new DateTime(2024, 5, 25, 23, 21, 11, 199, DateTimeKind.Local).AddTicks(1066) },
                    { 13, "id,corrupti,voluptatem,quaerat", "Intelligent Frozen Bacon", "est,ut,illo,dicta", new DateTime(2024, 8, 4, 19, 6, 31, 829, DateTimeKind.Local).AddTicks(8402) },
                    { 14, "praesentium,voluptatum,adipisci,voluptate", "Handcrafted Cotton Gloves", "dolorum,enim,dolor,illum", new DateTime(2024, 7, 21, 5, 50, 33, 883, DateTimeKind.Local).AddTicks(9323) },
                    { 15, "quas,quisquam,animi,corrupti", "Handcrafted Metal Fish", "eos,impedit,est,excepturi", new DateTime(2024, 4, 10, 22, 6, 7, 206, DateTimeKind.Local).AddTicks(2570) },
                    { 16, "ex,et,quisquam,dolorem", "Handcrafted Soft Cheese", "aliquid,odio,maxime,eaque", new DateTime(2023, 12, 21, 3, 56, 31, 36, DateTimeKind.Local).AddTicks(6134) },
                    { 17, "ipsa,iusto,vel,aspernatur", "Refined Frozen Tuna", "beatae,dolores,aperiam,aut", new DateTime(2024, 7, 19, 13, 20, 33, 653, DateTimeKind.Local).AddTicks(1928) },
                    { 18, "sit,in,sapiente,id", "Tasty Cotton Bike", "corporis,quis,culpa,quos", new DateTime(2024, 11, 13, 3, 30, 36, 856, DateTimeKind.Local).AddTicks(2120) },
                    { 19, "tempore,blanditiis,esse,qui", "Ergonomic Steel Pizza", "accusamus,sit,nam,cupiditate", new DateTime(2024, 7, 14, 15, 48, 53, 258, DateTimeKind.Local).AddTicks(2107) },
                    { 20, "iste,voluptate,blanditiis,nobis", "Incredible Metal Bacon", "aut,sunt,repudiandae,quos", new DateTime(2024, 10, 22, 16, 2, 35, 410, DateTimeKind.Local).AddTicks(7584) },
                    { 21, "a,aspernatur,veniam,fuga", "Refined Rubber Tuna", "quisquam,sequi,nisi,aut", new DateTime(2024, 10, 4, 11, 21, 22, 875, DateTimeKind.Local).AddTicks(6757) },
                    { 22, "enim,aperiam,ipsam,ut", "Small Soft Chair", "vitae,et,iste,eligendi", new DateTime(2024, 6, 13, 0, 29, 4, 773, DateTimeKind.Local).AddTicks(2733) },
                    { 23, "magni,quia,reprehenderit,placeat", "Sleek Rubber Computer", "excepturi,praesentium,eveniet,cum", new DateTime(2023, 11, 29, 9, 45, 56, 32, DateTimeKind.Local).AddTicks(9689) },
                    { 24, "aut,ut,omnis,illo", "Fantastic Frozen Chips", "quia,sint,quod,illo", new DateTime(2024, 6, 2, 13, 58, 20, 11, DateTimeKind.Local).AddTicks(5727) },
                    { 25, "perspiciatis,enim,aut,amet", "Handmade Cotton Shirt", "blanditiis,tenetur,distinctio,ut", new DateTime(2024, 2, 5, 0, 20, 32, 200, DateTimeKind.Local).AddTicks(7446) },
                    { 26, "exercitationem,aspernatur,eveniet,ex", "Practical Plastic Cheese", "quaerat,dignissimos,iure,ab", new DateTime(2024, 10, 2, 23, 51, 2, 63, DateTimeKind.Local).AddTicks(2289) },
                    { 27, "assumenda,nihil,in,saepe", "Generic Plastic Shoes", "voluptatem,qui,qui,possimus", new DateTime(2024, 10, 11, 18, 18, 52, 542, DateTimeKind.Local).AddTicks(5524) },
                    { 28, "aut,quis,incidunt,veniam", "Licensed Frozen Shoes", "similique,enim,et,voluptas", new DateTime(2024, 6, 5, 11, 41, 58, 251, DateTimeKind.Local).AddTicks(4016) },
                    { 29, "beatae,et,laboriosam,totam", "Practical Metal Keyboard", "hic,dolore,quae,qui", new DateTime(2024, 3, 17, 0, 9, 32, 700, DateTimeKind.Local).AddTicks(9824) },
                    { 30, "neque,architecto,eum,autem", "Gorgeous Fresh Shoes", "est,voluptatem,tempore,maiores", new DateTime(2024, 7, 9, 0, 2, 6, 378, DateTimeKind.Local).AddTicks(5426) },
                    { 31, "qui,rerum,voluptatem,ex", "Licensed Frozen Shoes", "in,voluptatem,repellendus,dolorem", new DateTime(2024, 8, 10, 20, 5, 55, 355, DateTimeKind.Local).AddTicks(7321) },
                    { 32, "beatae,non,nihil,inventore", "Gorgeous Metal Mouse", "sunt,et,est,quia", new DateTime(2024, 11, 4, 3, 9, 29, 926, DateTimeKind.Local).AddTicks(1919) },
                    { 33, "consectetur,harum,quasi,vel", "Rustic Wooden Sausages", "omnis,dolorem,quaerat,vel", new DateTime(2024, 1, 15, 17, 59, 47, 124, DateTimeKind.Local).AddTicks(8561) },
                    { 34, "maxime,cupiditate,impedit,fugit", "Licensed Wooden Hat", "et,ut,maxime,nam", new DateTime(2024, 4, 24, 18, 31, 7, 658, DateTimeKind.Local).AddTicks(7424) },
                    { 35, "magni,nesciunt,eos,enim", "Ergonomic Cotton Table", "debitis,voluptatem,voluptas,ut", new DateTime(2023, 12, 4, 19, 11, 8, 285, DateTimeKind.Local).AddTicks(5101) },
                    { 36, "repellat,omnis,nemo,facilis", "Handcrafted Concrete Hat", "debitis,et,est,quia", new DateTime(2024, 4, 30, 23, 0, 23, 40, DateTimeKind.Local).AddTicks(282) },
                    { 37, "earum,culpa,eius,vitae", "Sleek Soft Keyboard", "porro,aut,modi,quod", new DateTime(2024, 7, 2, 7, 25, 15, 299, DateTimeKind.Local).AddTicks(9416) },
                    { 38, "error,voluptates,beatae,aut", "Unbranded Cotton Table", "porro,doloremque,quod,magni", new DateTime(2024, 11, 3, 14, 52, 21, 226, DateTimeKind.Local).AddTicks(662) },
                    { 39, "maiores,error,perferendis,qui", "Small Plastic Soap", "consequatur,facere,nesciunt,tempora", new DateTime(2024, 1, 29, 23, 10, 2, 686, DateTimeKind.Local).AddTicks(7455) },
                    { 40, "dolorem,nulla,eum,non", "Awesome Rubber Keyboard", "aliquid,quia,quo,adipisci", new DateTime(2024, 2, 19, 1, 3, 59, 515, DateTimeKind.Local).AddTicks(1943) },
                    { 41, "iure,officia,ipsum,beatae", "Handcrafted Steel Salad", "maiores,quasi,aliquam,nisi", new DateTime(2024, 7, 20, 9, 56, 9, 666, DateTimeKind.Local).AddTicks(5581) },
                    { 42, "vel,velit,dolore,voluptas", "Practical Rubber Soap", "velit,repellendus,commodi,commodi", new DateTime(2024, 10, 13, 15, 55, 16, 343, DateTimeKind.Local).AddTicks(7443) },
                    { 43, "et,molestiae,magni,qui", "Incredible Cotton Shirt", "laboriosam,eos,inventore,est", new DateTime(2024, 1, 17, 22, 31, 44, 725, DateTimeKind.Local).AddTicks(7220) },
                    { 44, "esse,ut,accusamus,dolore", "Incredible Steel Mouse", "vel,dolorem,ipsam,sunt", new DateTime(2024, 7, 10, 18, 50, 57, 940, DateTimeKind.Local).AddTicks(6950) },
                    { 45, "cum,cum,ea,sit", "Gorgeous Plastic Ball", "dolore,nesciunt,ut,reprehenderit", new DateTime(2024, 9, 19, 21, 2, 41, 732, DateTimeKind.Local).AddTicks(1748) },
                    { 46, "perferendis,et,impedit,culpa", "Gorgeous Soft Ball", "laboriosam,exercitationem,accusamus,vero", new DateTime(2024, 1, 21, 12, 9, 20, 769, DateTimeKind.Local).AddTicks(1826) },
                    { 47, "sed,ducimus,ut,repellendus", "Refined Wooden Table", "odit,quaerat,asperiores,a", new DateTime(2024, 8, 13, 0, 13, 19, 772, DateTimeKind.Local).AddTicks(9978) },
                    { 48, "pariatur,ut,itaque,laborum", "Refined Wooden Chair", "aut,et,totam,aut", new DateTime(2023, 12, 12, 20, 6, 43, 457, DateTimeKind.Local).AddTicks(9801) },
                    { 49, "officiis,provident,est,aut", "Practical Fresh Salad", "quia,quia,enim,enim", new DateTime(2024, 9, 10, 1, 13, 11, 415, DateTimeKind.Local).AddTicks(7052) },
                    { 50, "impedit,consequuntur,non,debitis", "Fantastic Cotton Tuna", "consequatur,possimus,aut,quis", new DateTime(2024, 11, 13, 17, 38, 5, 594, DateTimeKind.Local).AddTicks(4203) },
                    { 51, "itaque,ullam,voluptatem,ducimus", "Tasty Metal Bike", "voluptates,quis,exercitationem,quod", new DateTime(2024, 1, 2, 10, 58, 35, 410, DateTimeKind.Local).AddTicks(6555) },
                    { 52, "aspernatur,ut,sed,consequuntur", "Practical Steel Salad", "beatae,accusantium,et,et", new DateTime(2024, 7, 12, 16, 55, 11, 922, DateTimeKind.Local).AddTicks(917) },
                    { 53, "nemo,quos,vero,beatae", "Handmade Wooden Pants", "aut,ea,commodi,sit", new DateTime(2024, 4, 16, 14, 45, 21, 751, DateTimeKind.Local).AddTicks(3476) },
                    { 54, "animi,dolorem,vel,voluptate", "Tasty Fresh Mouse", "error,tenetur,rerum,magnam", new DateTime(2024, 2, 24, 9, 9, 39, 198, DateTimeKind.Local).AddTicks(4954) },
                    { 55, "totam,nihil,est,facere", "Intelligent Concrete Chicken", "et,voluptatum,sunt,mollitia", new DateTime(2024, 7, 9, 19, 20, 40, 454, DateTimeKind.Local).AddTicks(2672) },
                    { 56, "consequatur,fugit,voluptatibus,autem", "Generic Rubber Gloves", "et,nemo,vitae,saepe", new DateTime(2024, 7, 29, 3, 48, 18, 75, DateTimeKind.Local).AddTicks(9494) },
                    { 57, "autem,repudiandae,odit,totam", "Fantastic Concrete Computer", "molestiae,non,id,quos", new DateTime(2024, 6, 21, 13, 32, 42, 159, DateTimeKind.Local).AddTicks(853) },
                    { 58, "accusantium,ex,similique,cumque", "Intelligent Frozen Salad", "voluptate,eius,suscipit,dolores", new DateTime(2024, 6, 9, 10, 18, 6, 16, DateTimeKind.Local).AddTicks(8935) },
                    { 59, "tenetur,porro,illo,doloribus", "Unbranded Plastic Shirt", "esse,consequatur,ut,a", new DateTime(2024, 4, 29, 1, 26, 14, 526, DateTimeKind.Local).AddTicks(4182) },
                    { 60, "voluptas,autem,in,est", "Awesome Granite Towels", "nulla,quia,porro,at", new DateTime(2024, 11, 21, 7, 55, 45, 0, DateTimeKind.Local).AddTicks(7088) },
                    { 61, "minima,ab,dolores,animi", "Ergonomic Frozen Towels", "est,autem,dolorem,eligendi", new DateTime(2024, 4, 9, 21, 19, 18, 170, DateTimeKind.Local).AddTicks(6527) },
                    { 62, "quas,accusantium,et,vitae", "Tasty Granite Shirt", "quia,consectetur,soluta,similique", new DateTime(2024, 5, 7, 18, 9, 11, 474, DateTimeKind.Local).AddTicks(1507) },
                    { 63, "vero,fugit,adipisci,excepturi", "Licensed Concrete Shirt", "enim,id,et,voluptas", new DateTime(2024, 9, 17, 19, 9, 9, 828, DateTimeKind.Local).AddTicks(5890) },
                    { 64, "architecto,quasi,maxime,fuga", "Generic Granite Chips", "minima,occaecati,impedit,voluptatem", new DateTime(2024, 2, 9, 22, 32, 57, 969, DateTimeKind.Local).AddTicks(9081) },
                    { 65, "vitae,aperiam,qui,recusandae", "Gorgeous Steel Ball", "rem,ducimus,perferendis,est", new DateTime(2024, 10, 20, 12, 43, 7, 188, DateTimeKind.Local).AddTicks(4468) },
                    { 66, "libero,debitis,quasi,incidunt", "Handcrafted Cotton Chair", "velit,autem,odit,et", new DateTime(2024, 1, 7, 4, 22, 14, 874, DateTimeKind.Local).AddTicks(1368) },
                    { 67, "quis,similique,quibusdam,et", "Fantastic Frozen Fish", "officia,dolore,ipsa,quaerat", new DateTime(2024, 1, 13, 0, 11, 29, 100, DateTimeKind.Local).AddTicks(3545) },
                    { 68, "aut,sit,id,perferendis", "Fantastic Soft Chips", "velit,repellat,natus,qui", new DateTime(2024, 7, 3, 17, 51, 11, 143, DateTimeKind.Local).AddTicks(1507) },
                    { 69, "tenetur,corrupti,commodi,iste", "Tasty Soft Car", "quo,eaque,officia,pariatur", new DateTime(2024, 10, 7, 17, 26, 11, 977, DateTimeKind.Local).AddTicks(5083) },
                    { 70, "deserunt,id,modi,qui", "Tasty Frozen Chair", "nihil,aut,qui,non", new DateTime(2024, 4, 17, 3, 50, 49, 512, DateTimeKind.Local).AddTicks(4404) },
                    { 71, "eveniet,recusandae,eum,sint", "Awesome Soft Car", "aut,tempore,eum,fuga", new DateTime(2024, 11, 19, 7, 50, 0, 979, DateTimeKind.Local).AddTicks(5724) },
                    { 72, "sapiente,nihil,temporibus,debitis", "Handcrafted Metal Towels", "enim,quidem,consectetur,enim", new DateTime(2023, 12, 20, 21, 17, 26, 516, DateTimeKind.Local).AddTicks(5383) },
                    { 73, "a,tempora,totam,corrupti", "Handmade Metal Computer", "incidunt,quod,dolores,inventore", new DateTime(2024, 6, 12, 15, 13, 21, 641, DateTimeKind.Local).AddTicks(4177) },
                    { 74, "voluptatem,impedit,beatae,vel", "Tasty Concrete Pizza", "natus,dolore,quia,dolorum", new DateTime(2024, 1, 12, 8, 17, 48, 776, DateTimeKind.Local).AddTicks(8585) },
                    { 75, "adipisci,odio,asperiores,ad", "Awesome Wooden Pizza", "officia,molestiae,quia,accusantium", new DateTime(2024, 9, 8, 21, 6, 4, 60, DateTimeKind.Local).AddTicks(4870) },
                    { 76, "doloribus,voluptate,corporis,et", "Incredible Frozen Ball", "ut,placeat,mollitia,sint", new DateTime(2024, 2, 20, 0, 25, 56, 100, DateTimeKind.Local).AddTicks(1941) },
                    { 77, "non,odio,natus,quae", "Practical Soft Chair", "architecto,numquam,sit,tenetur", new DateTime(2024, 3, 9, 23, 39, 31, 238, DateTimeKind.Local).AddTicks(2830) },
                    { 78, "architecto,quaerat,aut,quibusdam", "Awesome Concrete Car", "blanditiis,quia,qui,officia", new DateTime(2024, 3, 2, 9, 30, 10, 430, DateTimeKind.Local).AddTicks(2070) },
                    { 79, "sit,ea,hic,rem", "Sleek Steel Car", "ex,temporibus,placeat,modi", new DateTime(2024, 3, 23, 6, 13, 28, 839, DateTimeKind.Local).AddTicks(6827) },
                    { 80, "qui,magnam,aut,qui", "Practical Granite Keyboard", "consequuntur,fugiat,illo,distinctio", new DateTime(2024, 4, 21, 23, 12, 47, 836, DateTimeKind.Local).AddTicks(948) },
                    { 81, "alias,odit,nobis,necessitatibus", "Awesome Granite Soap", "ratione,dolores,saepe,quo", new DateTime(2024, 3, 6, 19, 22, 40, 740, DateTimeKind.Local).AddTicks(3566) },
                    { 82, "veritatis,voluptates,maxime,culpa", "Small Fresh Pizza", "qui,incidunt,nam,beatae", new DateTime(2024, 6, 11, 13, 30, 16, 209, DateTimeKind.Local).AddTicks(1765) },
                    { 83, "debitis,voluptatem,minus,deserunt", "Incredible Plastic Chips", "voluptatum,est,aut,sed", new DateTime(2024, 4, 14, 21, 6, 54, 351, DateTimeKind.Local).AddTicks(2008) },
                    { 84, "inventore,ipsum,est,illum", "Gorgeous Fresh Salad", "quis,in,nisi,suscipit", new DateTime(2024, 5, 2, 5, 18, 16, 211, DateTimeKind.Local).AddTicks(2637) },
                    { 85, "ipsam,adipisci,placeat,suscipit", "Ergonomic Concrete Salad", "perferendis,eaque,cumque,quis", new DateTime(2024, 8, 3, 1, 11, 54, 378, DateTimeKind.Local).AddTicks(5214) },
                    { 86, "incidunt,perferendis,qui,et", "Generic Steel Fish", "voluptatibus,quia,officiis,officia", new DateTime(2024, 10, 4, 2, 25, 33, 83, DateTimeKind.Local).AddTicks(6629) },
                    { 87, "est,exercitationem,quos,et", "Small Steel Table", "omnis,at,rem,accusantium", new DateTime(2024, 10, 15, 13, 10, 59, 903, DateTimeKind.Local).AddTicks(5486) },
                    { 88, "ex,quae,odit,autem", "Handmade Rubber Car", "eius,dolor,est,quia", new DateTime(2024, 5, 13, 20, 20, 8, 611, DateTimeKind.Local).AddTicks(9591) },
                    { 89, "accusantium,consequatur,quos,at", "Ergonomic Frozen Car", "quidem,magnam,id,modi", new DateTime(2023, 12, 12, 12, 46, 4, 504, DateTimeKind.Local).AddTicks(4824) },
                    { 90, "ut,illo,harum,voluptate", "Small Metal Chair", "iure,nihil,nemo,est", new DateTime(2024, 11, 3, 20, 5, 31, 470, DateTimeKind.Local).AddTicks(4788) },
                    { 91, "odit,eos,consectetur,sunt", "Licensed Cotton Chair", "et,ut,cupiditate,aliquam", new DateTime(2024, 9, 21, 4, 5, 46, 781, DateTimeKind.Local).AddTicks(7155) },
                    { 92, "alias,ab,ut,quos", "Gorgeous Rubber Cheese", "quae,repellat,ipsa,quos", new DateTime(2024, 8, 25, 6, 52, 58, 340, DateTimeKind.Local).AddTicks(9787) },
                    { 93, "sed,ea,quia,enim", "Practical Steel Bike", "velit,sed,dolorum,in", new DateTime(2024, 5, 15, 21, 49, 22, 135, DateTimeKind.Local).AddTicks(8050) },
                    { 94, "aut,qui,optio,facilis", "Licensed Rubber Keyboard", "incidunt,sit,aspernatur,modi", new DateTime(2024, 8, 23, 0, 50, 55, 316, DateTimeKind.Local).AddTicks(6509) },
                    { 95, "inventore,est,provident,fugit", "Refined Plastic Salad", "et,molestias,quia,aut", new DateTime(2024, 1, 24, 21, 28, 58, 814, DateTimeKind.Local).AddTicks(7897) },
                    { 96, "neque,quibusdam,ipsa,eos", "Small Frozen Table", "beatae,vitae,ex,provident", new DateTime(2024, 7, 10, 21, 42, 35, 89, DateTimeKind.Local).AddTicks(2155) },
                    { 97, "impedit,consequatur,et,possimus", "Unbranded Granite Ball", "harum,vel,voluptates,ipsa", new DateTime(2024, 5, 16, 5, 12, 14, 496, DateTimeKind.Local).AddTicks(964) },
                    { 98, "natus,eum,praesentium,qui", "Handcrafted Concrete Computer", "vel,unde,facilis,et", new DateTime(2024, 4, 17, 16, 55, 49, 977, DateTimeKind.Local).AddTicks(3844) },
                    { 99, "officia,possimus,illum,ea", "Ergonomic Steel Chips", "mollitia,ut,et,praesentium", new DateTime(2023, 12, 29, 15, 10, 12, 44, DateTimeKind.Local).AddTicks(7409) },
                    { 100, "qui,nihil,sequi,optio", "Ergonomic Soft Car", "temporibus,dolorem,quo,nesciunt", new DateTime(2024, 4, 12, 19, 22, 15, 920, DateTimeKind.Local).AddTicks(9099) },
                    { 101, "sunt,et,ipsam,optio", "Refined Granite Ball", "voluptatem,accusantium,quia,odio", new DateTime(2024, 10, 4, 22, 56, 15, 106, DateTimeKind.Local).AddTicks(3055) },
                    { 102, "qui,voluptas,rem,aut", "Rustic Rubber Shoes", "dolorem,et,nihil,quam", new DateTime(2024, 8, 21, 22, 26, 48, 748, DateTimeKind.Local).AddTicks(6678) },
                    { 103, "quis,ipsum,beatae,voluptas", "Generic Concrete Pizza", "soluta,minus,recusandae,voluptatem", new DateTime(2024, 11, 15, 17, 6, 48, 793, DateTimeKind.Local).AddTicks(7977) },
                    { 104, "velit,repellat,itaque,molestias", "Licensed Granite Pizza", "et,debitis,laboriosam,sint", new DateTime(2024, 7, 22, 19, 16, 39, 274, DateTimeKind.Local).AddTicks(644) },
                    { 105, "fugit,aut,sed,tenetur", "Tasty Wooden Chair", "et,in,temporibus,quisquam", new DateTime(2023, 12, 24, 23, 51, 0, 983, DateTimeKind.Local).AddTicks(7148) },
                    { 106, "dolores,dolorum,qui,odit", "Practical Rubber Shirt", "illo,omnis,enim,beatae", new DateTime(2024, 3, 5, 21, 55, 14, 44, DateTimeKind.Local).AddTicks(3003) },
                    { 107, "incidunt,id,non,a", "Licensed Soft Tuna", "sint,quia,ut,sunt", new DateTime(2024, 7, 27, 8, 51, 20, 280, DateTimeKind.Local).AddTicks(3887) },
                    { 108, "architecto,esse,perspiciatis,beatae", "Intelligent Steel Salad", "aut,rerum,tempore,veritatis", new DateTime(2024, 3, 30, 0, 36, 25, 535, DateTimeKind.Local).AddTicks(7045) },
                    { 109, "ipsum,aspernatur,voluptatem,quisquam", "Licensed Concrete Pants", "enim,consequatur,cumque,voluptas", new DateTime(2024, 7, 22, 16, 0, 25, 650, DateTimeKind.Local).AddTicks(4540) },
                    { 110, "voluptatibus,mollitia,ut,autem", "Generic Cotton Gloves", "dolorum,id,officiis,totam", new DateTime(2024, 5, 20, 1, 19, 30, 584, DateTimeKind.Local).AddTicks(6346) },
                    { 111, "enim,commodi,dolorem,qui", "Gorgeous Cotton Chair", "mollitia,sequi,sit,commodi", new DateTime(2024, 3, 14, 19, 22, 34, 560, DateTimeKind.Local).AddTicks(3022) },
                    { 112, "dolores,rerum,doloribus,laborum", "Rustic Wooden Gloves", "cum,libero,aut,voluptate", new DateTime(2024, 9, 18, 9, 42, 37, 353, DateTimeKind.Local).AddTicks(4435) },
                    { 113, "autem,quo,itaque,accusamus", "Awesome Steel Table", "rerum,placeat,est,et", new DateTime(2024, 11, 15, 12, 28, 35, 541, DateTimeKind.Local).AddTicks(1416) },
                    { 114, "quis,hic,modi,sunt", "Incredible Granite Sausages", "soluta,nihil,excepturi,adipisci", new DateTime(2024, 4, 8, 9, 44, 44, 418, DateTimeKind.Local).AddTicks(1311) },
                    { 115, "voluptates,tempore,reiciendis,et", "Practical Plastic Keyboard", "laborum,numquam,delectus,eos", new DateTime(2024, 2, 20, 20, 18, 1, 713, DateTimeKind.Local).AddTicks(9630) },
                    { 116, "optio,quasi,placeat,neque", "Refined Rubber Gloves", "est,velit,quia,quia", new DateTime(2024, 9, 5, 10, 21, 33, 784, DateTimeKind.Local).AddTicks(2927) },
                    { 117, "rem,ducimus,magni,natus", "Handmade Soft Gloves", "omnis,incidunt,et,aspernatur", new DateTime(2024, 2, 18, 0, 33, 51, 711, DateTimeKind.Local).AddTicks(8897) },
                    { 118, "corporis,odio,est,esse", "Sleek Wooden Salad", "asperiores,vitae,laborum,suscipit", new DateTime(2024, 9, 11, 9, 2, 52, 453, DateTimeKind.Local).AddTicks(328) },
                    { 119, "architecto,provident,sed,necessitatibus", "Intelligent Frozen Table", "autem,sed,quia,sed", new DateTime(2024, 9, 14, 8, 12, 48, 941, DateTimeKind.Local).AddTicks(1336) },
                    { 120, "ea,quia,quisquam,ea", "Generic Soft Computer", "autem,accusantium,et,laboriosam", new DateTime(2024, 5, 2, 7, 2, 52, 992, DateTimeKind.Local).AddTicks(8539) },
                    { 121, "et,tempore,facere,necessitatibus", "Small Rubber Shirt", "reprehenderit,aperiam,est,culpa", new DateTime(2024, 10, 30, 9, 23, 59, 656, DateTimeKind.Local).AddTicks(3581) },
                    { 122, "aliquam,omnis,et,quasi", "Handcrafted Steel Table", "doloremque,aut,dolores,consequatur", new DateTime(2024, 5, 12, 22, 49, 15, 924, DateTimeKind.Local).AddTicks(635) },
                    { 123, "maxime,quasi,vitae,eos", "Handmade Cotton Car", "sed,quas,rerum,nostrum", new DateTime(2024, 11, 11, 14, 21, 19, 823, DateTimeKind.Local).AddTicks(4262) },
                    { 124, "fuga,ea,sequi,et", "Handmade Fresh Tuna", "nesciunt,quod,libero,praesentium", new DateTime(2023, 12, 29, 4, 42, 28, 857, DateTimeKind.Local).AddTicks(1872) },
                    { 125, "totam,cum,labore,voluptatum", "Incredible Granite Chair", "non,ad,eius,voluptate", new DateTime(2024, 3, 7, 16, 54, 8, 604, DateTimeKind.Local).AddTicks(8969) },
                    { 126, "alias,deleniti,eligendi,sit", "Ergonomic Rubber Pants", "occaecati,eligendi,dolores,autem", new DateTime(2024, 4, 10, 11, 2, 0, 229, DateTimeKind.Local).AddTicks(8138) },
                    { 127, "et,voluptatem,dolor,tenetur", "Small Metal Tuna", "eum,beatae,asperiores,explicabo", new DateTime(2024, 6, 14, 19, 6, 0, 467, DateTimeKind.Local).AddTicks(2595) },
                    { 128, "dolor,cupiditate,nam,eos", "Small Rubber Pants", "ut,sit,ipsa,soluta", new DateTime(2023, 12, 25, 16, 28, 56, 1, DateTimeKind.Local).AddTicks(7886) },
                    { 129, "amet,nihil,et,dignissimos", "Generic Steel Keyboard", "quia,ullam,repellendus,quos", new DateTime(2024, 11, 14, 3, 59, 39, 833, DateTimeKind.Local).AddTicks(8610) },
                    { 130, "ad,ad,voluptatem,quod", "Tasty Metal Towels", "consequatur,quo,sit,voluptatum", new DateTime(2023, 12, 24, 8, 27, 29, 786, DateTimeKind.Local).AddTicks(3941) },
                    { 131, "deleniti,nesciunt,cumque,consectetur", "Ergonomic Frozen Chips", "voluptas,dolore,delectus,dicta", new DateTime(2024, 4, 14, 1, 33, 3, 591, DateTimeKind.Local).AddTicks(3286) },
                    { 132, "quis,soluta,nesciunt,eaque", "Fantastic Fresh Soap", "at,est,et,inventore", new DateTime(2024, 8, 26, 22, 53, 1, 657, DateTimeKind.Local).AddTicks(6542) },
                    { 133, "eius,facilis,fugit,dolores", "Rustic Wooden Soap", "et,magni,enim,impedit", new DateTime(2024, 8, 5, 6, 13, 25, 368, DateTimeKind.Local).AddTicks(1923) },
                    { 134, "labore,ducimus,architecto,qui", "Fantastic Steel Hat", "est,et,repudiandae,fugiat", new DateTime(2024, 9, 16, 1, 51, 18, 20, DateTimeKind.Local).AddTicks(3909) },
                    { 135, "temporibus,occaecati,et,consequatur", "Small Fresh Fish", "laboriosam,quia,provident,ut", new DateTime(2024, 9, 5, 12, 45, 9, 386, DateTimeKind.Local).AddTicks(1989) },
                    { 136, "voluptatum,rem,sit,maiores", "Tasty Metal Gloves", "quia,eum,dolores,nihil", new DateTime(2024, 10, 10, 18, 13, 14, 751, DateTimeKind.Local).AddTicks(7712) },
                    { 137, "ratione,officia,et,et", "Fantastic Plastic Computer", "sit,magni,et,eos", new DateTime(2024, 5, 23, 23, 6, 33, 679, DateTimeKind.Local).AddTicks(2712) },
                    { 138, "velit,officiis,minus,placeat", "Licensed Metal Pants", "aut,qui,voluptas,labore", new DateTime(2024, 6, 11, 11, 8, 54, 712, DateTimeKind.Local).AddTicks(9711) },
                    { 139, "quos,soluta,est,aut", "Practical Frozen Gloves", "minus,maiores,est,id", new DateTime(2024, 1, 5, 21, 50, 36, 24, DateTimeKind.Local).AddTicks(9893) },
                    { 140, "saepe,deserunt,deserunt,quos", "Licensed Fresh Fish", "eos,optio,consequatur,ut", new DateTime(2024, 4, 13, 7, 39, 52, 91, DateTimeKind.Local).AddTicks(1185) },
                    { 141, "error,dignissimos,et,est", "Awesome Plastic Chicken", "molestiae,fugit,eos,reprehenderit", new DateTime(2024, 11, 14, 5, 32, 48, 174, DateTimeKind.Local).AddTicks(7792) },
                    { 142, "doloribus,eveniet,ducimus,vitae", "Handcrafted Soft Cheese", "consequatur,repellendus,sunt,est", new DateTime(2024, 1, 14, 17, 52, 13, 382, DateTimeKind.Local).AddTicks(5717) },
                    { 143, "autem,expedita,odio,error", "Handmade Frozen Bike", "et,et,voluptatem,sit", new DateTime(2024, 9, 28, 8, 3, 14, 61, DateTimeKind.Local).AddTicks(6854) },
                    { 144, "aut,qui,maiores,in", "Generic Cotton Chips", "consequatur,libero,ipsa,voluptatem", new DateTime(2024, 3, 16, 8, 59, 23, 896, DateTimeKind.Local).AddTicks(851) },
                    { 145, "sunt,id,dolore,ut", "Fantastic Wooden Pizza", "voluptatem,doloribus,eum,minus", new DateTime(2024, 10, 1, 10, 2, 22, 147, DateTimeKind.Local).AddTicks(7160) },
                    { 146, "quia,aut,nisi,et", "Fantastic Plastic Towels", "sed,quae,ducimus,temporibus", new DateTime(2024, 6, 2, 13, 33, 20, 348, DateTimeKind.Local).AddTicks(2119) },
                    { 147, "praesentium,ut,et,libero", "Generic Soft Chicken", "qui,sit,quo,eos", new DateTime(2024, 3, 30, 21, 50, 29, 422, DateTimeKind.Local).AddTicks(604) },
                    { 148, "dolore,omnis,sint,id", "Generic Granite Cheese", "laboriosam,exercitationem,est,doloremque", new DateTime(2024, 6, 7, 7, 24, 32, 736, DateTimeKind.Local).AddTicks(2666) },
                    { 149, "et,rerum,voluptates,quam", "Refined Plastic Computer", "voluptatem,illo,illo,dolor", new DateTime(2024, 6, 4, 7, 40, 5, 496, DateTimeKind.Local).AddTicks(9527) },
                    { 150, "est,magni,eos,et", "Awesome Soft Soap", "at,ducimus,et,ut", new DateTime(2024, 5, 29, 17, 25, 54, 542, DateTimeKind.Local).AddTicks(5049) },
                    { 151, "mollitia,dolores,unde,cumque", "Practical Metal Pants", "sed,aut,incidunt,dolore", new DateTime(2024, 10, 8, 13, 7, 32, 342, DateTimeKind.Local).AddTicks(185) },
                    { 152, "expedita,rem,assumenda,maiores", "Unbranded Cotton Soap", "quasi,at,quis,vel", new DateTime(2024, 7, 4, 1, 4, 15, 447, DateTimeKind.Local).AddTicks(188) },
                    { 153, "iure,aspernatur,velit,dolorem", "Handmade Granite Pizza", "illum,tempora,ut,dignissimos", new DateTime(2023, 12, 28, 0, 48, 57, 464, DateTimeKind.Local).AddTicks(3362) },
                    { 154, "consequatur,quis,repellat,iusto", "Awesome Wooden Pants", "quam,eos,harum,iste", new DateTime(2024, 3, 24, 21, 9, 5, 100, DateTimeKind.Local).AddTicks(962) },
                    { 155, "voluptatum,itaque,libero,nam", "Handmade Wooden Hat", "deleniti,omnis,ut,voluptatem", new DateTime(2024, 2, 16, 23, 55, 37, 826, DateTimeKind.Local).AddTicks(5422) },
                    { 156, "ut,qui,voluptas,et", "Handmade Granite Bacon", "ullam,earum,et,voluptas", new DateTime(2024, 4, 9, 10, 27, 25, 731, DateTimeKind.Local).AddTicks(1978) },
                    { 157, "libero,eius,facere,velit", "Licensed Cotton Mouse", "eos,voluptate,quia,suscipit", new DateTime(2024, 2, 6, 3, 5, 45, 603, DateTimeKind.Local).AddTicks(2564) },
                    { 158, "perferendis,repellendus,molestias,error", "Licensed Plastic Towels", "praesentium,assumenda,eos,eveniet", new DateTime(2024, 8, 25, 1, 9, 33, 913, DateTimeKind.Local).AddTicks(4820) },
                    { 159, "distinctio,beatae,mollitia,voluptate", "Handmade Wooden Chair", "et,tempora,in,laborum", new DateTime(2024, 1, 27, 2, 24, 0, 324, DateTimeKind.Local).AddTicks(8538) },
                    { 160, "ipsum,velit,itaque,voluptatibus", "Awesome Plastic Bike", "omnis,voluptatibus,ea,natus", new DateTime(2024, 2, 1, 6, 52, 52, 532, DateTimeKind.Local).AddTicks(574) },
                    { 161, "laboriosam,sunt,debitis,error", "Fantastic Frozen Car", "quos,quo,deserunt,cum", new DateTime(2024, 6, 28, 17, 25, 40, 363, DateTimeKind.Local).AddTicks(7388) },
                    { 162, "dolores,aspernatur,odit,quam", "Rustic Metal Soap", "et,et,omnis,pariatur", new DateTime(2024, 4, 21, 12, 17, 18, 390, DateTimeKind.Local).AddTicks(8967) },
                    { 163, "rerum,et,est,ea", "Awesome Metal Pants", "corporis,error,et,est", new DateTime(2024, 9, 28, 22, 29, 56, 872, DateTimeKind.Local).AddTicks(44) },
                    { 164, "qui,necessitatibus,odit,molestias", "Small Rubber Chair", "sint,est,ipsa,aut", new DateTime(2024, 1, 16, 20, 46, 0, 669, DateTimeKind.Local).AddTicks(9530) },
                    { 165, "blanditiis,qui,rerum,autem", "Handcrafted Steel Hat", "ut,voluptatem,quo,maiores", new DateTime(2024, 1, 14, 8, 55, 51, 455, DateTimeKind.Local).AddTicks(5621) },
                    { 166, "itaque,exercitationem,molestiae,iste", "Rustic Rubber Mouse", "totam,totam,quas,est", new DateTime(2024, 9, 10, 18, 16, 16, 70, DateTimeKind.Local).AddTicks(6200) },
                    { 167, "est,optio,explicabo,neque", "Rustic Frozen Chair", "occaecati,adipisci,non,ut", new DateTime(2024, 3, 8, 23, 7, 36, 736, DateTimeKind.Local).AddTicks(7585) },
                    { 168, "autem,dolores,sint,itaque", "Practical Wooden Pants", "maxime,porro,cumque,ut", new DateTime(2024, 8, 28, 14, 44, 6, 384, DateTimeKind.Local).AddTicks(3808) },
                    { 169, "hic,esse,rerum,laboriosam", "Incredible Soft Chair", "velit,consequatur,iusto,voluptas", new DateTime(2024, 7, 15, 1, 1, 23, 639, DateTimeKind.Local).AddTicks(2074) },
                    { 170, "dicta,repellendus,laborum,velit", "Handcrafted Metal Computer", "quasi,velit,et,est", new DateTime(2024, 8, 20, 6, 49, 4, 522, DateTimeKind.Local).AddTicks(8570) },
                    { 171, "repellat,eos,nobis,error", "Sleek Steel Chicken", "commodi,illo,libero,magnam", new DateTime(2024, 11, 7, 17, 33, 0, 166, DateTimeKind.Local).AddTicks(6613) },
                    { 172, "suscipit,amet,adipisci,aperiam", "Awesome Soft Bike", "corporis,ullam,numquam,ut", new DateTime(2024, 10, 20, 5, 12, 25, 280, DateTimeKind.Local).AddTicks(5798) },
                    { 173, "enim,in,eos,eos", "Generic Concrete Shirt", "itaque,nobis,aliquam,soluta", new DateTime(2024, 5, 15, 5, 14, 27, 634, DateTimeKind.Local).AddTicks(4165) },
                    { 174, "et,minus,enim,amet", "Intelligent Fresh Sausages", "sunt,qui,molestiae,aut", new DateTime(2024, 6, 9, 7, 24, 53, 895, DateTimeKind.Local).AddTicks(8919) },
                    { 175, "et,quis,pariatur,earum", "Practical Metal Ball", "dolorem,magnam,quae,voluptates", new DateTime(2024, 8, 22, 8, 45, 45, 491, DateTimeKind.Local).AddTicks(2791) },
                    { 176, "illo,quam,consequatur,ut", "Gorgeous Rubber Salad", "quae,qui,aspernatur,quis", new DateTime(2024, 7, 10, 15, 16, 11, 692, DateTimeKind.Local).AddTicks(7325) },
                    { 177, "natus,ratione,repellat,at", "Small Cotton Cheese", "enim,velit,excepturi,magni", new DateTime(2024, 9, 16, 22, 0, 14, 937, DateTimeKind.Local).AddTicks(8215) },
                    { 178, "explicabo,nobis,enim,ut", "Fantastic Steel Pants", "aliquam,voluptates,in,occaecati", new DateTime(2024, 2, 25, 16, 8, 39, 965, DateTimeKind.Local).AddTicks(9876) },
                    { 179, "laboriosam,quisquam,aliquid,recusandae", "Awesome Frozen Keyboard", "perspiciatis,qui,unde,veritatis", new DateTime(2024, 5, 4, 14, 29, 37, 570, DateTimeKind.Local).AddTicks(635) },
                    { 180, "maiores,pariatur,nesciunt,facilis", "Incredible Rubber Computer", "itaque,blanditiis,et,ipsam", new DateTime(2024, 8, 24, 1, 21, 3, 505, DateTimeKind.Local).AddTicks(9646) },
                    { 181, "eaque,qui,autem,expedita", "Handcrafted Steel Pants", "rerum,facere,eius,omnis", new DateTime(2024, 8, 3, 5, 2, 3, 215, DateTimeKind.Local).AddTicks(7602) },
                    { 182, "quae,iusto,reiciendis,ut", "Practical Frozen Pizza", "possimus,non,quod,odio", new DateTime(2024, 5, 24, 7, 42, 48, 655, DateTimeKind.Local).AddTicks(1135) },
                    { 183, "quia,delectus,error,vero", "Refined Wooden Mouse", "vitae,ullam,aut,sint", new DateTime(2024, 1, 5, 13, 46, 54, 14, DateTimeKind.Local).AddTicks(168) },
                    { 184, "officia,et,ex,illo", "Incredible Granite Chicken", "voluptas,natus,non,aperiam", new DateTime(2024, 3, 24, 11, 38, 22, 203, DateTimeKind.Local).AddTicks(628) },
                    { 185, "error,voluptates,est,atque", "Small Steel Keyboard", "modi,doloribus,et,rerum", new DateTime(2024, 1, 7, 14, 43, 4, 818, DateTimeKind.Local).AddTicks(6665) },
                    { 186, "nihil,asperiores,suscipit,repudiandae", "Ergonomic Frozen Pizza", "id,voluptatibus,maxime,ratione", new DateTime(2024, 2, 11, 12, 25, 8, 343, DateTimeKind.Local).AddTicks(9289) },
                    { 187, "inventore,necessitatibus,occaecati,ipsa", "Awesome Metal Pants", "iste,eaque,et,dignissimos", new DateTime(2024, 6, 12, 4, 58, 48, 698, DateTimeKind.Local).AddTicks(4644) },
                    { 188, "provident,qui,dolores,et", "Tasty Metal Chair", "dolorum,voluptatibus,optio,expedita", new DateTime(2023, 11, 27, 6, 7, 16, 660, DateTimeKind.Local).AddTicks(8693) },
                    { 189, "voluptates,expedita,veritatis,non", "Sleek Cotton Cheese", "eligendi,omnis,nam,fugit", new DateTime(2024, 11, 11, 21, 44, 10, 934, DateTimeKind.Local).AddTicks(7986) },
                    { 190, "praesentium,nostrum,consequatur,assumenda", "Ergonomic Rubber Chicken", "totam,aspernatur,est,ipsam", new DateTime(2024, 10, 3, 8, 21, 17, 765, DateTimeKind.Local).AddTicks(4867) },
                    { 191, "ipsam,nulla,numquam,veritatis", "Rustic Granite Soap", "laborum,consequatur,ut,illo", new DateTime(2024, 9, 25, 3, 23, 16, 559, DateTimeKind.Local).AddTicks(2264) },
                    { 192, "aut,sit,temporibus,eligendi", "Unbranded Plastic Chair", "debitis,earum,in,error", new DateTime(2023, 12, 24, 19, 18, 34, 264, DateTimeKind.Local).AddTicks(6638) },
                    { 193, "eligendi,voluptates,praesentium,vel", "Handcrafted Soft Sausages", "ullam,voluptates,sed,suscipit", new DateTime(2024, 5, 30, 20, 26, 54, 481, DateTimeKind.Local).AddTicks(5088) },
                    { 194, "veniam,mollitia,earum,voluptates", "Generic Wooden Cheese", "optio,voluptatem,mollitia,est", new DateTime(2024, 5, 8, 12, 13, 30, 191, DateTimeKind.Local).AddTicks(5774) },
                    { 195, "temporibus,laboriosam,dolorem,blanditiis", "Sleek Steel Pants", "corrupti,ipsam,sunt,quidem", new DateTime(2024, 11, 10, 17, 26, 36, 456, DateTimeKind.Local).AddTicks(185) },
                    { 196, "natus,libero,voluptatibus,ducimus", "Ergonomic Metal Keyboard", "expedita,iure,est,dolorem", new DateTime(2024, 8, 5, 14, 58, 47, 79, DateTimeKind.Local).AddTicks(982) },
                    { 197, "animi,nisi,ipsam,quae", "Rustic Wooden Table", "nostrum,beatae,id,corporis", new DateTime(2024, 2, 13, 17, 32, 27, 110, DateTimeKind.Local).AddTicks(7300) },
                    { 198, "similique,aut,et,nihil", "Awesome Rubber Computer", "dicta,autem,id,voluptas", new DateTime(2024, 9, 27, 15, 0, 34, 970, DateTimeKind.Local).AddTicks(8893) },
                    { 199, "a,magni,omnis,aliquid", "Sleek Granite Bike", "sint,doloremque,nesciunt,rerum", new DateTime(2024, 6, 14, 14, 8, 26, 23, DateTimeKind.Local).AddTicks(3654) },
                    { 200, "hic,quae,maiores,voluptatem", "Rustic Rubber Keyboard", "quaerat,corporis,et,voluptatibus", new DateTime(2024, 10, 16, 6, 57, 6, 499, DateTimeKind.Local).AddTicks(2802) }
                });

            migrationBuilder.InsertData(
                table: "Studios",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Feil - Kassulke" },
                    { 2, "Koepp Group" },
                    { 3, "Koss Inc" },
                    { 4, "Hegmann, Larkin and Lowe" },
                    { 5, "Stamm, Pacocha and Ortiz" },
                    { 6, "Homenick - Swift" },
                    { 7, "Hilpert - Cummerata" },
                    { 8, "Murray - Hyatt" },
                    { 9, "Mills Group" },
                    { 10, "Wehner - Prohaska" },
                    { 11, "Borer - Wiza" },
                    { 12, "Franecki - Greenholt" },
                    { 13, "Kihn - Torp" },
                    { 14, "Wunsch - Anderson" },
                    { 15, "Murray, Gulgowski and Mayert" },
                    { 16, "Berge Inc" },
                    { 17, "DuBuque, Koepp and Nolan" },
                    { 18, "Botsford Group" },
                    { 19, "Hills Group" },
                    { 20, "Cronin, Abernathy and Marks" },
                    { 21, "Schulist Inc" },
                    { 22, "Wiegand - Christiansen" },
                    { 23, "Marquardt, Parker and Murphy" },
                    { 24, "Brekke and Sons" },
                    { 25, "Rau, Greenfelder and Baumbach" },
                    { 26, "DuBuque LLC" },
                    { 27, "Osinski, Heller and Ebert" },
                    { 28, "Reilly - Hermiston" },
                    { 29, "Ernser - Cremin" },
                    { 30, "Herman, Kling and Stark" },
                    { 31, "Keeling - Adams" },
                    { 32, "Borer - Bins" },
                    { 33, "O'Reilly - Oberbrunner" },
                    { 34, "Hirthe Inc" },
                    { 35, "Goodwin Group" },
                    { 36, "Daniel, Herzog and Bruen" },
                    { 37, "Strosin, Dietrich and Prosacco" },
                    { 38, "Frami, Botsford and Pagac" },
                    { 39, "Balistreri LLC" },
                    { 40, "Altenwerth, Labadie and Stokes" },
                    { 41, "Lindgren and Sons" },
                    { 42, "Lockman, Bergnaum and Casper" },
                    { 43, "Pacocha LLC" },
                    { 44, "Lockman - Johnson" },
                    { 45, "Runte, Kertzmann and Von" },
                    { 46, "Gerhold and Sons" },
                    { 47, "Hettinger LLC" },
                    { 48, "Osinski - Runolfsdottir" },
                    { 49, "Jaskolski, Becker and Schamberger" },
                    { 50, "Hahn Inc" },
                    { 51, "Koelpin, Ryan and Herman" },
                    { 52, "Hilll, Flatley and McCullough" },
                    { 53, "Barrows LLC" },
                    { 54, "Sawayn Inc" },
                    { 55, "Crooks - Bergstrom" },
                    { 56, "Koelpin - Hammes" },
                    { 57, "Cronin - Dickens" },
                    { 58, "Hamill, Hackett and Rempel" },
                    { 59, "Adams - Oberbrunner" },
                    { 60, "Nicolas, Daniel and Leuschke" },
                    { 61, "Mertz, Yundt and Hartmann" },
                    { 62, "Bartell LLC" },
                    { 63, "Koss and Sons" },
                    { 64, "Schamberger, Simonis and Berge" },
                    { 65, "Price - Kub" },
                    { 66, "Morissette - Jaskolski" },
                    { 67, "Gorczany, Doyle and Johnston" },
                    { 68, "Wisoky, Lindgren and Luettgen" },
                    { 69, "Krajcik - Johnson" },
                    { 70, "White and Sons" },
                    { 71, "Paucek - Zulauf" },
                    { 72, "Jacobs LLC" },
                    { 73, "Lubowitz, Swaniawski and Kunze" },
                    { 74, "Pouros, Hodkiewicz and Ratke" },
                    { 75, "Shanahan, Goodwin and Gorczany" },
                    { 76, "DuBuque - Herman" },
                    { 77, "McClure, Heathcote and Carter" },
                    { 78, "Senger, Rowe and Haley" },
                    { 79, "Hettinger - Ebert" },
                    { 80, "Block - Schneider" },
                    { 81, "Gutmann - Lind" },
                    { 82, "Schinner, Collier and Paucek" },
                    { 83, "Willms - Nicolas" },
                    { 84, "Lynch, West and Dach" },
                    { 85, "Legros, Daugherty and Jenkins" },
                    { 86, "Brown Group" },
                    { 87, "McLaughlin, Schaden and Will" },
                    { 88, "Nicolas, Hansen and Durgan" },
                    { 89, "Hilpert, White and Goodwin" },
                    { 90, "Rosenbaum, Bahringer and Ernser" },
                    { 91, "Streich - Nikolaus" },
                    { 92, "Hamill - Hartmann" },
                    { 93, "Barrows - Goldner" },
                    { 94, "Volkman, Ziemann and Pollich" },
                    { 95, "Schaefer, Raynor and Botsford" },
                    { 96, "Carter Group" },
                    { 97, "Haag, Rutherford and Kemmer" },
                    { 98, "Fay LLC" },
                    { 99, "Nienow - Schamberger" },
                    { 100, "Wisoky LLC" },
                    { 101, "Brekke - Sauer" },
                    { 102, "Abbott and Sons" },
                    { 103, "Bernhard, Gorczany and Grady" },
                    { 104, "Considine, Kassulke and Nader" },
                    { 105, "Johns LLC" },
                    { 106, "Yundt and Sons" },
                    { 107, "Wintheiser, Schamberger and Cassin" },
                    { 108, "Mosciski, Auer and Simonis" },
                    { 109, "Crooks, Stokes and Carroll" },
                    { 110, "Bashirian - Jenkins" },
                    { 111, "Heller, Schaefer and McKenzie" },
                    { 112, "Lesch LLC" },
                    { 113, "Rippin and Sons" },
                    { 114, "Weber - Gerlach" },
                    { 115, "Howell Inc" },
                    { 116, "Lindgren - Nolan" },
                    { 117, "Greenholt, Greenholt and Von" },
                    { 118, "Ernser - Nikolaus" },
                    { 119, "Stoltenberg - Beahan" },
                    { 120, "Jacobs - Conn" },
                    { 121, "Quitzon, Franecki and Walter" },
                    { 122, "Upton Inc" },
                    { 123, "Altenwerth - Monahan" },
                    { 124, "Balistreri, Haag and Stracke" },
                    { 125, "Bashirian Inc" },
                    { 126, "Green, Effertz and Russel" },
                    { 127, "Ondricka Inc" },
                    { 128, "Torphy, Bogisich and McClure" },
                    { 129, "Feil and Sons" },
                    { 130, "McGlynn - Goyette" },
                    { 131, "Olson Group" },
                    { 132, "Gutkowski LLC" },
                    { 133, "Upton and Sons" },
                    { 134, "Konopelski and Sons" },
                    { 135, "Cronin - Cassin" },
                    { 136, "Wunsch - Prohaska" },
                    { 137, "Legros - Barton" },
                    { 138, "Toy LLC" },
                    { 139, "Beahan, Upton and Stiedemann" },
                    { 140, "O'Kon - Volkman" },
                    { 141, "Maggio Group" },
                    { 142, "Hills - Buckridge" },
                    { 143, "Hettinger Inc" },
                    { 144, "Casper, Feest and Powlowski" },
                    { 145, "Blick, Swaniawski and Ondricka" },
                    { 146, "Marquardt - King" },
                    { 147, "Schinner, Haley and Effertz" },
                    { 148, "Gleichner - Hartmann" },
                    { 149, "Jast - Pouros" },
                    { 150, "Larson, Reilly and Walter" },
                    { 151, "Kunde, Heaney and Walker" },
                    { 152, "Jacobs and Sons" },
                    { 153, "Hirthe - Rau" },
                    { 154, "Kuphal, Zulauf and Harber" },
                    { 155, "Ledner and Sons" },
                    { 156, "Goyette Inc" },
                    { 157, "Keeling - Schultz" },
                    { 158, "Schinner and Sons" },
                    { 159, "Sawayn Group" },
                    { 160, "Sauer Inc" },
                    { 161, "Ritchie Group" },
                    { 162, "Pacocha and Sons" },
                    { 163, "Hayes, Wiza and Ziemann" },
                    { 164, "Orn LLC" },
                    { 165, "Cummings - Frami" },
                    { 166, "Deckow Inc" },
                    { 167, "Schaden, Roob and Reilly" },
                    { 168, "Bahringer, Stehr and Shields" },
                    { 169, "Dach - Becker" },
                    { 170, "Boyer, Lebsack and Kunze" },
                    { 171, "Bednar Group" },
                    { 172, "O'Hara and Sons" },
                    { 173, "Tremblay Inc" },
                    { 174, "Koepp, Sawayn and Marquardt" },
                    { 175, "Quitzon - Hintz" },
                    { 176, "Mills - Cormier" },
                    { 177, "Ritchie Inc" },
                    { 178, "Daniel - Beahan" },
                    { 179, "Kuhlman Inc" },
                    { 180, "Parisian Group" },
                    { 181, "Harvey, Leuschke and Mills" },
                    { 182, "Koss - Cartwright" },
                    { 183, "Kerluke - Emard" },
                    { 184, "Cartwright Inc" },
                    { 185, "Bernhard - Bartell" },
                    { 186, "Rodriguez - Nicolas" },
                    { 187, "Kreiger LLC" },
                    { 188, "Murphy, Marvin and Nienow" },
                    { 189, "Smitham LLC" },
                    { 190, "Fisher - Shanahan" },
                    { 191, "Ziemann Group" },
                    { 192, "Kessler - Ryan" },
                    { 193, "Wolf - Brakus" },
                    { 194, "Schulist Group" },
                    { 195, "Stoltenberg, Kuvalis and Schroeder" },
                    { 196, "McDermott - Beatty" },
                    { 197, "Swift LLC" },
                    { 198, "Hyatt LLC" },
                    { 199, "Nicolas, Rice and Howell" },
                    { 200, "Fritsch Group" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_GameEditors_GamesId",
                table: "GameEditors",
                column: "GamesId");

            migrationBuilder.CreateIndex(
                name: "IX_GameStudios_StudiosId",
                table: "GameStudios",
                column: "StudiosId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "GameEditors");

            migrationBuilder.DropTable(
                name: "GameStudios");

            migrationBuilder.DropTable(
                name: "Editors");

            migrationBuilder.DropTable(
                name: "Games");

            migrationBuilder.DropTable(
                name: "Studios");
        }
    }
}
